"""Reusable model mixins."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import Uuid, func
from sqlalchemy.orm import Mapped, mapped_column

from app.persistence.types import UtcDateTime


def utc_now() -> datetime:
    """Application-side UTC timestamp."""
    return datetime.now(UTC)


class UuidPrimaryKeyMixin:
    """A UUID primary key generated by the application.

    Generated in Python rather than by the database so that an entity has its
    identity *before* it is inserted. That matters for the order flow: the
    order intent, its client order id and its audit record all have to reference
    the same identity before anything reaches the exchange.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Creation and update timestamps, both UTC."""

    created_at: Mapped[datetime] = mapped_column(
        UtcDateTime,
        nullable=False,
        default=utc_now,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        UtcDateTime,
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=func.now(),
    )


class CreatedAtMixin:
    """Creation timestamp only, for append-only records.

    Audit and event rows deliberately have no ``updated_at``: they are never
    modified. A record that can be updated is not an audit trail.
    """

    created_at: Mapped[datetime] = mapped_column(
        UtcDateTime,
        nullable=False,
        default=utc_now,
        server_default=func.now(),
    )
