"""candle time series

Revision ID: 3bb1a49f1c27
Revises: c77ffbcb838d
Create Date: 2026-07-30 12:57:06.452482+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3bb1a49f1c27"
down_revision: str | None = "c77ffbcb838d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candle",
        sa.Column("trading_pair_id", sa.Uuid(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "15m", "1h", "4h", "1d", name="timeframe", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("high_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("low_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("close_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("volume", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("quote_volume", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "REST_BACKFILL",
                "REST_GAP_FILL",
                "WEBSOCKET",
                name="candle_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("close_price > 0", name=op.f("ck_candle_close_positive")),
        sa.CheckConstraint(
            "close_price >= low_price AND close_price <= high_price",
            name=op.f("ck_candle_close_within_range"),
        ),
        sa.CheckConstraint("close_time > open_time", name=op.f("ck_candle_close_after_open")),
        sa.CheckConstraint("high_price > 0", name=op.f("ck_candle_high_positive")),
        sa.CheckConstraint("high_price >= low_price", name=op.f("ck_candle_high_at_least_low")),
        sa.CheckConstraint("low_price > 0", name=op.f("ck_candle_low_positive")),
        sa.CheckConstraint("open_price > 0", name=op.f("ck_candle_open_positive")),
        sa.CheckConstraint(
            "open_price >= low_price AND open_price <= high_price",
            name=op.f("ck_candle_open_within_range"),
        ),
        sa.CheckConstraint("quote_volume >= 0", name=op.f("ck_candle_quote_volume_non_negative")),
        sa.CheckConstraint("trade_count >= 0", name=op.f("ck_candle_trade_count_non_negative")),
        sa.CheckConstraint("volume >= 0", name=op.f("ck_candle_volume_non_negative")),
        sa.ForeignKeyConstraint(
            ["trading_pair_id"],
            ["trading_pair.id"],
            name=op.f("fk_candle_trading_pair_id_trading_pair"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "trading_pair_id", "timeframe", "open_time", name=op.f("pk_candle")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candle")
    # ### end Alembic commands ###
