"""orders fills positions trades and snapshots

Revision ID: c77ffbcb838d
Revises: b3c4e83f3f61
Create Date: 2026-07-30 12:24:09.507779+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c77ffbcb838d"
down_revision: str | None = "b3c4e83f3f61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balance_snapshot",
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "venue",
            sa.Enum(
                "PAPER",
                "LIVE",
                "BACKTEST",
                name="execution_venue",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("free_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("locked_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("trading_day_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("free_amount >= 0", name=op.f("ck_balance_snapshot_free_non_negative")),
        sa.CheckConstraint(
            "locked_amount >= 0", name=op.f("ck_balance_snapshot_locked_non_negative")
        ),
        sa.CheckConstraint(
            "total_amount = free_amount + locked_amount",
            name=op.f("ck_balance_snapshot_total_equals_free_plus_locked"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_balance_snapshot_trading_day_id_trading_day"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_balance_snapshot")),
    )
    op.create_index("ix_balance_snapshot_taken_at", "balance_snapshot", ["taken_at"], unique=False)
    op.create_index(
        op.f("ix_balance_snapshot_trading_day_id"),
        "balance_snapshot",
        ["trading_day_id"],
        unique=False,
    )
    op.create_index(
        "ix_balance_snapshot_venue_asset",
        "balance_snapshot",
        ["venue", "asset", "taken_at"],
        unique=False,
    )
    op.create_table(
        "pnl_snapshot",
        sa.Column("trading_day_id", sa.Uuid(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("realised_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unrealised_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("net_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fees_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("equity_quote", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("open_position_count", sa.Integer(), nullable=False),
        sa.Column("funding_rate_ron_per_quote", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("net_pnl_ron", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "funding_rate_ron_per_quote > 0", name=op.f("ck_pnl_snapshot_funding_rate_positive")
        ),
        sa.CheckConstraint(
            "net_pnl_quote = realised_pnl_quote + unrealised_pnl_quote",
            name=op.f("ck_pnl_snapshot_net_equals_realised_plus_unrealised"),
        ),
        sa.CheckConstraint(
            "open_position_count >= 0",
            name=op.f("ck_pnl_snapshot_open_position_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_pnl_snapshot_trading_day_id_trading_day"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pnl_snapshot")),
    )
    op.create_index(
        "ix_pnl_snapshot_day_taken_at", "pnl_snapshot", ["trading_day_id", "taken_at"], unique=False
    )
    op.create_table(
        "position",
        sa.Column("trading_pair_id", sa.Uuid(), nullable=False),
        sa.Column(
            "venue",
            sa.Enum(
                "PAPER",
                "LIVE",
                "BACKTEST",
                name="execution_venue",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("opened_trading_day_id", sa.Uuid(), nullable=False),
        sa.Column("closed_trading_day_id", sa.Uuid(), nullable=True),
        sa.Column("trading_session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPENING",
                "OPEN",
                "CLOSING",
                "CLOSED",
                "DESYNCED",
                "ABANDONED",
                name="position_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="order_side", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("stop_loss_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("take_profit_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("risk_amount_quote", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("unrealised_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("desync_detail", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("entry_price > 0", name=op.f("ck_position_entry_price_positive")),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_position_quantity_non_negative")),
        sa.CheckConstraint(
            "stop_loss_price IS NULL OR stop_loss_price > 0",
            name=op.f("ck_position_stop_loss_price_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["closed_trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_position_closed_trading_day_id_trading_day"),
        ),
        sa.ForeignKeyConstraint(
            ["opened_trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_position_opened_trading_day_id_trading_day"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_pair_id"],
            ["trading_pair.id"],
            name=op.f("fk_position_trading_pair_id_trading_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_session_id"],
            ["trading_session.id"],
            name=op.f("fk_position_trading_session_id_trading_session"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position")),
    )
    op.create_index(
        op.f("ix_position_opened_trading_day_id"),
        "position",
        ["opened_trading_day_id"],
        unique=False,
    )
    op.create_index("ix_position_status", "position", ["status"], unique=False)
    op.create_index("ix_position_venue_status", "position", ["venue", "status"], unique=False)
    op.create_table(
        "trade",
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("trading_pair_id", sa.Uuid(), nullable=False),
        sa.Column(
            "venue",
            sa.Enum(
                "PAPER",
                "LIVE",
                "BACKTEST",
                name="execution_venue",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("opened_trading_day_id", sa.Uuid(), nullable=False),
        sa.Column("closed_trading_day_id", sa.Uuid(), nullable=False),
        sa.Column("trading_session_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("gross_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fees_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("slippage_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("net_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("risk_amount_quote", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("r_multiple", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("is_win", sa.Boolean(), nullable=False),
        sa.Column(
            "exit_reason",
            sa.Enum(
                "STOP_LOSS",
                "TAKE_PROFIT",
                "MANUAL",
                "SESSION_CLOSE",
                "DAY_STOP",
                "EMERGENCY_STOP",
                "RECONCILIATION",
                name="exit_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("closed_at >= opened_at", name=op.f("ck_trade_closed_after_opened")),
        sa.CheckConstraint("entry_price > 0", name=op.f("ck_trade_entry_price_positive")),
        sa.CheckConstraint("exit_price > 0", name=op.f("ck_trade_exit_price_positive")),
        sa.CheckConstraint("fees_quote >= 0", name=op.f("ck_trade_fees_non_negative")),
        sa.CheckConstraint(
            "is_win = (net_pnl_quote > 0)", name=op.f("ck_trade_is_win_matches_net")
        ),
        sa.CheckConstraint(
            "net_pnl_quote = gross_pnl_quote - fees_quote - slippage_quote",
            name=op.f("ck_trade_net_equals_gross_minus_costs"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_trade_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["closed_trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_trade_closed_trading_day_id_trading_day"),
        ),
        sa.ForeignKeyConstraint(
            ["opened_trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_trade_opened_trading_day_id_trading_day"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["position.id"], name=op.f("fk_trade_position_id_position")
        ),
        sa.ForeignKeyConstraint(
            ["trading_pair_id"],
            ["trading_pair.id"],
            name=op.f("fk_trade_trading_pair_id_trading_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_session_id"],
            ["trading_session.id"],
            name=op.f("fk_trade_trading_session_id_trading_session"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade")),
        sa.UniqueConstraint("position_id", name=op.f("uq_trade_position_id")),
    )
    op.create_index("ix_trade_closed_at", "trade", ["closed_at"], unique=False)
    op.create_index(
        "ix_trade_closed_trading_day_id", "trade", ["closed_trading_day_id"], unique=False
    )
    op.create_index(
        "ix_trade_opened_trading_day_id", "trade", ["opened_trading_day_id"], unique=False
    )
    op.create_table(
        "order",
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=64), nullable=True),
        sa.Column(
            "venue",
            sa.Enum(
                "PAPER",
                "LIVE",
                "BACKTEST",
                name="execution_venue",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("trading_day_id", sa.Uuid(), nullable=False),
        sa.Column("trading_session_id", sa.Uuid(), nullable=True),
        sa.Column("trading_pair_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=True),
        sa.Column("risk_assessment_id", sa.Uuid(), nullable=True),
        sa.Column("position_id", sa.Uuid(), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum(
                "ENTRY",
                "STOP_LOSS",
                "TAKE_PROFIT",
                "MANUAL_EXIT",
                "SESSION_CLOSE",
                "RECONCILIATION_CLOSE",
                name="order_purpose",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="order_side", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "LIMIT", "MARKET", name="order_type", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "time_in_force",
            sa.Enum(
                "GTC", "IOC", "FOK", name="time_in_force", native_enum=False, create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "INTENT_RECORDED",
                "SUBMITTING",
                "ACCEPTED",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELED",
                "EXPIRED",
                "REJECTED",
                "UNKNOWN",
                "RECONCILING",
                "UNRESOLVED",
                name="order_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("requested_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("filled_quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("average_fill_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("fee_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fee_currency", sa.String(length=10), nullable=True),
        sa.Column("intent_recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.String(length=128), nullable=True),
        sa.Column("reconciliation_attempts", sa.Integer(), nullable=False),
        sa.Column("last_reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exchange_request", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("exchange_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose <> 'ENTRY' OR risk_assessment_id IS NOT NULL",
            name=op.f("ck_order_entry_requires_risk_approval"),
        ),
        sa.CheckConstraint(
            "type <> 'LIMIT' OR requested_price IS NOT NULL",
            name=op.f("ck_order_limit_order_has_price"),
        ),
        sa.CheckConstraint("fee_amount >= 0", name=op.f("ck_order_fee_non_negative")),
        sa.CheckConstraint(
            "filled_quantity <= requested_quantity",
            name=op.f("ck_order_filled_not_above_requested"),
        ),
        sa.CheckConstraint(
            "filled_quantity >= 0", name=op.f("ck_order_filled_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "reconciliation_attempts >= 0",
            name=op.f("ck_order_reconciliation_attempts_non_negative"),
        ),
        sa.CheckConstraint(
            "requested_price IS NULL OR requested_price > 0",
            name=op.f("ck_order_requested_price_positive"),
        ),
        sa.CheckConstraint(
            "requested_quantity > 0", name=op.f("ck_order_requested_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["position.id"], name=op.f("fk_order_position_id_position")
        ),
        sa.ForeignKeyConstraint(
            ["risk_assessment_id"],
            ["risk_assessment.id"],
            name=op.f("fk_order_risk_assessment_id_risk_assessment"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signal.id"], name=op.f("fk_order_signal_id_signal")
        ),
        sa.ForeignKeyConstraint(
            ["trading_day_id"], ["trading_day.id"], name=op.f("fk_order_trading_day_id_trading_day")
        ),
        sa.ForeignKeyConstraint(
            ["trading_pair_id"],
            ["trading_pair.id"],
            name=op.f("fk_order_trading_pair_id_trading_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_session_id"],
            ["trading_session.id"],
            name=op.f("fk_order_trading_session_id_trading_session"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
        sa.UniqueConstraint("client_order_id", name=op.f("uq_order_client_order_id")),
    )
    op.create_index("ix_order_correlation_id", "order", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_order_position_id"), "order", ["position_id"], unique=False)
    op.create_index("ix_order_status", "order", ["status"], unique=False)
    op.create_index("ix_order_trading_day_id", "order", ["trading_day_id"], unique=False)
    op.create_index(
        "uq_order_exchange_order_id",
        "order",
        ["venue", "exchange_order_id"],
        unique=True,
        postgresql_where=sa.text("exchange_order_id IS NOT NULL"),
    )
    op.create_table(
        "order_fill",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("exchange_trade_id", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("fee_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fee_currency", sa.String(length=10), nullable=True),
        sa.Column("is_maker", sa.Boolean(), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fee_amount >= 0", name=op.f("ck_order_fill_fee_non_negative")),
        sa.CheckConstraint("price > 0", name=op.f("ck_order_fill_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_fill_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
            name=op.f("fk_order_fill_order_id_order"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_fill")),
    )
    op.create_index("ix_order_fill_filled_at", "order_fill", ["filled_at"], unique=False)
    op.create_index(op.f("ix_order_fill_order_id"), "order_fill", ["order_id"], unique=False)
    op.create_index(
        "uq_order_fill_exchange_trade_id",
        "order_fill",
        ["order_id", "exchange_trade_id"],
        unique=True,
        postgresql_where=sa.text("exchange_trade_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_order_fill_exchange_trade_id",
        table_name="order_fill",
        postgresql_where=sa.text("exchange_trade_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_order_fill_order_id"), table_name="order_fill")
    op.drop_index("ix_order_fill_filled_at", table_name="order_fill")
    op.drop_table("order_fill")
    op.drop_index(
        "uq_order_exchange_order_id",
        table_name="order",
        postgresql_where=sa.text("exchange_order_id IS NOT NULL"),
    )
    op.drop_index("ix_order_trading_day_id", table_name="order")
    op.drop_index("ix_order_status", table_name="order")
    op.drop_index(op.f("ix_order_position_id"), table_name="order")
    op.drop_index("ix_order_correlation_id", table_name="order")
    op.drop_table("order")
    op.drop_index("ix_trade_opened_trading_day_id", table_name="trade")
    op.drop_index("ix_trade_closed_trading_day_id", table_name="trade")
    op.drop_index("ix_trade_closed_at", table_name="trade")
    op.drop_table("trade")
    op.drop_index("ix_position_venue_status", table_name="position")
    op.drop_index("ix_position_status", table_name="position")
    op.drop_index(op.f("ix_position_opened_trading_day_id"), table_name="position")
    op.drop_table("position")
    op.drop_index("ix_pnl_snapshot_day_taken_at", table_name="pnl_snapshot")
    op.drop_table("pnl_snapshot")
    op.drop_index("ix_balance_snapshot_venue_asset", table_name="balance_snapshot")
    op.drop_index(op.f("ix_balance_snapshot_trading_day_id"), table_name="balance_snapshot")
    op.drop_index("ix_balance_snapshot_taken_at", table_name="balance_snapshot")
    op.drop_table("balance_snapshot")
    # ### end Alembic commands ###
