"""trading day and trading session

Revision ID: 88f3d5bda42d
Revises: 063918b4ec49
Create Date: 2026-07-30 12:02:53.544691+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "88f3d5bda42d"
down_revision: str | None = "063918b4ec49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_day",
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "TRADING_SUSPENDED",
                "DAILY_TARGET_REACHED",
                "DAILY_STOP_REACHED",
                "MANUALLY_STOPPED",
                "TECHNICAL_FAILURE",
                "CLOSED",
                name="trading_day_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "ACTIVE_TRADING",
                "NO_TRADE",
                "TRADING_SUSPENDED",
                "DAILY_TARGET_REACHED",
                "DAILY_STOP_REACHED",
                "MANUALLY_STOPPED",
                "TECHNICAL_FAILURE",
                name="trading_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("risk_configuration_id", sa.Uuid(), nullable=False),
        sa.Column("trading_configuration_id", sa.Uuid(), nullable=False),
        sa.Column("reporting_currency", sa.String(length=10), nullable=False),
        sa.Column("quote_currency", sa.String(length=10), nullable=False),
        sa.Column("reference_capital_ron", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("funding_rate_ron_per_quote", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("fx_rate_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("opening_equity_quote", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("closing_equity_quote", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("realised_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unrealised_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("gross_profit_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("gross_loss_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fees_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("slippage_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("session_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_losses", sa.Integer(), nullable=False),
        sa.Column("peak_realised_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("stop_reason", sa.String(length=64), nullable=True),
        sa.Column("stop_detail", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "consecutive_losses >= 0", name=op.f("ck_trading_day_consecutive_losses_non_negative")
        ),
        sa.CheckConstraint(
            "funding_rate_ron_per_quote > 0", name=op.f("ck_trading_day_funding_rate_positive")
        ),
        sa.CheckConstraint(
            "reference_capital_ron > 0", name=op.f("ck_trading_day_reference_capital_positive")
        ),
        sa.CheckConstraint(
            "session_count >= 0", name=op.f("ck_trading_day_session_count_non_negative")
        ),
        sa.CheckConstraint(
            "trade_count >= 0", name=op.f("ck_trading_day_trade_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["fx_rate_snapshot_id"],
            ["fx_rate_snapshot.id"],
            name=op.f("fk_trading_day_fx_rate_snapshot_id_fx_rate_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["risk_configuration_id"],
            ["risk_configuration.id"],
            name=op.f("fk_trading_day_risk_configuration_id_risk_configuration"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_configuration_id"],
            ["trading_configuration.id"],
            name=op.f("fk_trading_day_trading_configuration_id_trading_configuration"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_day")),
        sa.UniqueConstraint("trading_date", name=op.f("uq_trading_day_trading_date")),
    )
    op.create_index("ix_trading_day_status", "trading_day", ["status"], unique=False)
    op.create_table(
        "trading_session",
        sa.Column("trading_day_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EVALUATING",
                "OPEN",
                "CLOSING",
                "CLOSED_TARGET_REACHED",
                "CLOSED_RESTART_ELIGIBLE",
                "CLOSED_STOPPED",
                "CLOSED_NO_OPPORTUNITY",
                "ABORTED",
                name="trading_session_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realised_pnl_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fees_quote", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("close_reason", sa.String(length=64), nullable=True),
        sa.Column("close_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_trading_session_sequence_min")),
        sa.CheckConstraint(
            "trade_count >= 0", name=op.f("ck_trading_session_trade_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_trading_session_trading_day_id_trading_day"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_session")),
    )
    op.create_index("ix_trading_session_status", "trading_session", ["status"], unique=False)
    op.create_index(
        op.f("ix_trading_session_trading_day_id"),
        "trading_session",
        ["trading_day_id"],
        unique=False,
    )
    op.create_index(
        "uq_trading_session_sequence",
        "trading_session",
        ["trading_day_id", "sequence"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_trading_session_sequence", table_name="trading_session")
    op.drop_index(op.f("ix_trading_session_trading_day_id"), table_name="trading_session")
    op.drop_index("ix_trading_session_status", table_name="trading_session")
    op.drop_table("trading_session")
    op.drop_index("ix_trading_day_status", table_name="trading_day")
    op.drop_table("trading_day")
    # ### end Alembic commands ###
