"""reference configuration fx and audit tables

Revision ID: 063918b4ec49
Revises: 0001_baseline
Create Date: 2026-07-28 21:54:18.529248+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "063918b4ec49"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=True),
        sa.Column("aggregate_id", sa.Uuid(), nullable=True),
        sa.Column(
            "actor",
            sa.Enum(
                "SYSTEM",
                "OPERATOR",
                "STRATEGY",
                "RISK_ENGINE",
                "EXCHANGE",
                "SCHEDULER",
                name="audit_actor",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_detail", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("previous_state", sa.String(length=48), nullable=True),
        sa.Column("new_state", sa.String(length=48), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(
        "ix_audit_event_aggregate", "audit_event", ["aggregate_type", "aggregate_id"], unique=False
    )
    op.create_index(
        "ix_audit_event_correlation_id", "audit_event", ["correlation_id"], unique=False
    )
    op.create_index("ix_audit_event_event_type", "audit_event", ["event_type"], unique=False)
    op.create_index("ix_audit_event_occurred_at", "audit_event", ["occurred_at"], unique=False)
    op.create_table(
        "exchange",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange")),
        sa.UniqueConstraint("code", name=op.f("uq_exchange_code")),
    )
    op.create_table(
        "fx_rate_snapshot",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("base_currency", sa.String(length=10), nullable=False),
        sa.Column("quote_currency", sa.String(length=10), nullable=False),
        sa.Column("rate", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_currency <> quote_currency", name=op.f("ck_fx_rate_snapshot_currencies_differ")
        ),
        sa.CheckConstraint("rate > 0", name=op.f("ck_fx_rate_snapshot_rate_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rate_snapshot")),
        sa.UniqueConstraint(
            "source",
            "base_currency",
            "quote_currency",
            "rate_date",
            name="uq_fx_rate_snapshot_source_pair_date",
        ),
    )
    op.create_table(
        "risk_configuration",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("reference_capital_ron", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("reporting_currency", sa.String(length=10), nullable=False),
        sa.Column("session_target_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column(
            "session_restart_threshold_percent", sa.Numeric(precision=9, scale=4), nullable=False
        ),
        sa.Column("daily_maximum_loss_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column(
            "daily_pnl_basis",
            sa.Enum(
                "REALISED_ONLY",
                "REALISED_PLUS_UNREALISED",
                name="daily_pnl_basis",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("daily_profit_giveback_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column(
            "maximum_risk_per_trade_percent", sa.Numeric(precision=9, scale=4), nullable=False
        ),
        sa.Column("maximum_open_positions", sa.Integer(), nullable=False),
        sa.Column("maximum_trades_per_day", sa.Integer(), nullable=False),
        sa.Column("maximum_consecutive_losses", sa.Integer(), nullable=False),
        sa.Column("no_new_entry_minutes_before_day_end", sa.Integer(), nullable=False),
        sa.Column("max_candle_age_seconds", sa.Integer(), nullable=True),
        sa.Column("max_signal_age_seconds", sa.Integer(), nullable=True),
        sa.Column("max_spread_bps", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("min_order_book_depth_quote", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("min_atr_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("max_atr_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("min_reward_risk_ratio", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("max_estimated_slippage_bps", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("max_clock_drift_ms", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "daily_maximum_loss_percent > 0 AND daily_maximum_loss_percent <= 100",
            name=op.f("ck_risk_configuration_daily_maximum_loss_percent_range"),
        ),
        sa.CheckConstraint(
            "maximum_consecutive_losses >= 1",
            name=op.f("ck_risk_configuration_maximum_consecutive_losses_min"),
        ),
        sa.CheckConstraint(
            "maximum_open_positions >= 1",
            name=op.f("ck_risk_configuration_maximum_open_positions_min"),
        ),
        sa.CheckConstraint(
            "maximum_risk_per_trade_percent > 0 AND maximum_risk_per_trade_percent <= 100",
            name=op.f("ck_risk_configuration_maximum_risk_per_trade_percent_range"),
        ),
        sa.CheckConstraint(
            "maximum_trades_per_day >= 1",
            name=op.f("ck_risk_configuration_maximum_trades_per_day_min"),
        ),
        sa.CheckConstraint(
            "no_new_entry_minutes_before_day_end >= 0 AND no_new_entry_minutes_before_day_end <= 1440",
            name=op.f("ck_risk_configuration_no_new_entry_minutes_range"),
        ),
        sa.CheckConstraint(
            "reference_capital_ron > 0",
            name=op.f("ck_risk_configuration_reference_capital_positive"),
        ),
        sa.CheckConstraint(
            "session_target_percent > 0 AND session_target_percent <= 100",
            name=op.f("ck_risk_configuration_session_target_percent_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_configuration")),
        sa.UniqueConstraint("version", name=op.f("uq_risk_configuration_version")),
    )
    op.create_index(
        "uq_risk_configuration_active",
        "risk_configuration",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "system_event",
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "ERROR",
                "CRITICAL",
                name="event_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "health_status",
            sa.Enum(
                "STARTING",
                "HEALTHY",
                "DEGRADED",
                "UNHEALTHY",
                name="health_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_event")),
    )
    op.create_index("ix_system_event_category", "system_event", ["category"], unique=False)
    op.create_index("ix_system_event_occurred_at", "system_event", ["occurred_at"], unique=False)
    op.create_index("ix_system_event_severity", "system_event", ["severity"], unique=False)
    op.create_table(
        "trading_configuration",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "autonomy_mode",
            sa.Enum(
                "SIGNAL_ONLY",
                "PAPER_AUTOMATIC",
                "LIVE_AUTOMATIC",
                name="autonomy_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("emergency_stop_active", sa.Boolean(), nullable=False),
        sa.Column("emergency_stop_reason", sa.Text(), nullable=True),
        sa.Column("reporting_currency", sa.String(length=10), nullable=False),
        sa.Column("exchange_quote_currency", sa.String(length=10), nullable=False),
        sa.Column("trading_timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "primary_timeframe",
            sa.Enum(
                "15m",
                "1h",
                "4h",
                "1d",
                name="primary_timeframe",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("fx_rate_source", sa.String(length=32), nullable=False),
        sa.Column("usdt_usd_peg", sa.Numeric(precision=24, scale=12), nullable=False),
        sa.Column("trading_windows", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "usdt_usd_peg > 0", name=op.f("ck_trading_configuration_usdt_usd_peg_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_configuration")),
        sa.UniqueConstraint("version", name=op.f("uq_trading_configuration_version")),
    )
    op.create_index(
        "uq_trading_configuration_active",
        "trading_configuration",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "trading_pair",
        sa.Column("exchange_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("base_asset", sa.String(length=10), nullable=False),
        sa.Column("quote_asset", sa.String(length=10), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("exchange_status", sa.String(length=32), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("filters_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchange.id"],
            name=op.f("fk_trading_pair_exchange_id_exchange"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_pair")),
        sa.UniqueConstraint("exchange_id", "symbol", name="uq_trading_pair_symbol"),
    )
    op.create_index(
        op.f("ix_trading_pair_exchange_id"), "trading_pair", ["exchange_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trading_pair_exchange_id"), table_name="trading_pair")
    op.drop_table("trading_pair")
    op.drop_index(
        "uq_trading_configuration_active",
        table_name="trading_configuration",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("trading_configuration")
    op.drop_index("ix_system_event_severity", table_name="system_event")
    op.drop_index("ix_system_event_occurred_at", table_name="system_event")
    op.drop_index("ix_system_event_category", table_name="system_event")
    op.drop_table("system_event")
    op.drop_index(
        "uq_risk_configuration_active",
        table_name="risk_configuration",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("risk_configuration")
    op.drop_table("fx_rate_snapshot")
    op.drop_table("exchange")
    op.drop_index("ix_audit_event_occurred_at", table_name="audit_event")
    op.drop_index("ix_audit_event_event_type", table_name="audit_event")
    op.drop_index("ix_audit_event_correlation_id", table_name="audit_event")
    op.drop_index("ix_audit_event_aggregate", table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
