"""strategy signal and risk assessment

Revision ID: b3c4e83f3f61
Revises: 88f3d5bda42d
Create Date: 2026-07-30 12:10:07.498405+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b3c4e83f3f61"
down_revision: str | None = "88f3d5bda42d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategy",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy")),
        sa.UniqueConstraint("name", name=op.f("uq_strategy_name")),
    )
    op.create_table(
        "strategy_version",
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("code_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategy.id"],
            name=op.f("fk_strategy_version_strategy_id_strategy"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_version")),
    )
    op.create_index(
        op.f("ix_strategy_version_strategy_id"), "strategy_version", ["strategy_id"], unique=False
    )
    op.create_index(
        "uq_strategy_version_active",
        "strategy_version",
        ["strategy_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "uq_strategy_version_number", "strategy_version", ["strategy_id", "version"], unique=True
    )
    op.create_table(
        "signal",
        sa.Column("trading_day_id", sa.Uuid(), nullable=False),
        sa.Column("trading_session_id", sa.Uuid(), nullable=True),
        sa.Column("trading_pair_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "GENERATED",
                "RISK_APPROVED",
                "RISK_REJECTED",
                "AWAITING_OPERATOR",
                "OPERATOR_REJECTED",
                "ACCEPTED",
                "EXECUTED",
                "EXECUTION_FAILED",
                "EXPIRED",
                name="signal_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="order_side", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "timeframe",
            sa.Enum(
                "15m", "1h", "4h", "1d", name="timeframe", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("candle_open_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reference_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("stop_loss_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("take_profit_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("proposed_quantity", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("risk_amount_quote", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("reward_risk_ratio", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("score_components", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("strategy_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("market_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("operator_decision_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("operator_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "side <> 'BUY' OR stop_loss_price < reference_price",
            name=op.f("ck_signal_long_stop_below_entry"),
        ),
        sa.CheckConstraint(
            "side <> 'BUY' OR take_profit_price IS NULL OR take_profit_price > reference_price",
            name=op.f("ck_signal_long_target_above_entry"),
        ),
        sa.CheckConstraint("reference_price > 0", name=op.f("ck_signal_reference_price_positive")),
        sa.CheckConstraint("stop_loss_price > 0", name=op.f("ck_signal_stop_loss_price_positive")),
        sa.CheckConstraint(
            "take_profit_price IS NULL OR take_profit_price > 0",
            name=op.f("ck_signal_take_profit_price_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_version.id"],
            name=op.f("fk_signal_strategy_version_id_strategy_version"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_signal_trading_day_id_trading_day"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_pair_id"],
            ["trading_pair.id"],
            name=op.f("fk_signal_trading_pair_id_trading_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["trading_session_id"],
            ["trading_session.id"],
            name=op.f("fk_signal_trading_session_id_trading_session"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal")),
    )
    op.create_index("ix_signal_correlation_id", "signal", ["correlation_id"], unique=False)
    op.create_index(
        "ix_signal_pair_generated_at", "signal", ["trading_pair_id", "generated_at"], unique=False
    )
    op.create_index("ix_signal_status", "signal", ["status"], unique=False)
    op.create_index(
        op.f("ix_signal_strategy_version_id"), "signal", ["strategy_version_id"], unique=False
    )
    op.create_index(op.f("ix_signal_trading_day_id"), "signal", ["trading_day_id"], unique=False)
    op.create_table(
        "risk_assessment",
        sa.Column("signal_id", sa.Uuid(), nullable=True),
        sa.Column("trading_day_id", sa.Uuid(), nullable=False),
        sa.Column("risk_configuration_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "APPROVED",
                "REJECTED",
                name="risk_verdict",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason_codes", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("evaluated_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("approved_quantity", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("approved_risk_quote", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict <> 'REJECTED' OR cardinality(reason_codes) >= 1",
            name=op.f("ck_risk_assessment_rejection_has_reason_codes"),
        ),
        sa.ForeignKeyConstraint(
            ["risk_configuration_id"],
            ["risk_configuration.id"],
            name=op.f("fk_risk_assessment_risk_configuration_id_risk_configuration"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal.id"],
            name=op.f("fk_risk_assessment_signal_id_signal"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trading_day_id"],
            ["trading_day.id"],
            name=op.f("fk_risk_assessment_trading_day_id_trading_day"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_assessment")),
    )
    op.create_index(
        "ix_risk_assessment_correlation_id", "risk_assessment", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_risk_assessment_evaluated_at", "risk_assessment", ["evaluated_at"], unique=False
    )
    op.create_index(
        "ix_risk_assessment_reason_codes",
        "risk_assessment",
        ["reason_codes"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_risk_assessment_signal_id"), "risk_assessment", ["signal_id"], unique=False
    )
    op.create_index(
        op.f("ix_risk_assessment_trading_day_id"),
        "risk_assessment",
        ["trading_day_id"],
        unique=False,
    )
    op.create_index("ix_risk_assessment_verdict", "risk_assessment", ["verdict"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_risk_assessment_verdict", table_name="risk_assessment")
    op.drop_index(op.f("ix_risk_assessment_trading_day_id"), table_name="risk_assessment")
    op.drop_index(op.f("ix_risk_assessment_signal_id"), table_name="risk_assessment")
    op.drop_index(
        "ix_risk_assessment_reason_codes", table_name="risk_assessment", postgresql_using="gin"
    )
    op.drop_index("ix_risk_assessment_evaluated_at", table_name="risk_assessment")
    op.drop_index("ix_risk_assessment_correlation_id", table_name="risk_assessment")
    op.drop_table("risk_assessment")
    op.drop_index(op.f("ix_signal_trading_day_id"), table_name="signal")
    op.drop_index(op.f("ix_signal_strategy_version_id"), table_name="signal")
    op.drop_index("ix_signal_status", table_name="signal")
    op.drop_index("ix_signal_pair_generated_at", table_name="signal")
    op.drop_index("ix_signal_correlation_id", table_name="signal")
    op.drop_table("signal")
    op.drop_index("uq_strategy_version_number", table_name="strategy_version")
    op.drop_index(
        "uq_strategy_version_active",
        table_name="strategy_version",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_strategy_version_strategy_id"), table_name="strategy_version")
    op.drop_table("strategy_version")
    op.drop_table("strategy")
    # ### end Alembic commands ###
